import React from 'react';
import { BaseEmailTemplate } from './BaseEmailTemplate';
import { EmailTemplateData } from '@/lib/email-summary/types';

interface WeeklySummaryTemplateProps {
  data: EmailTemplateData;
}

/**
 * Weekly summary email template with comprehensive child development insights
 */
export const WeeklySummaryTemplate: React.FC<WeeklySummaryTemplateProps> = ({
  data,
}) => {
  const preheader = `${data.childName} had ${data.sessionCount} conversations this week with ${data.totalChatTime} total chat time`;

  return (
    <BaseEmailTemplate
      title={`${data.childName}&apos;s Week with Onda`}
      preheader={preheader}
    >
      {/* Header */}
      <div className="email-header">
        <h1>📊 {data.childName}&apos;s Week with Onda</h1>
        <p>{data.weekDateRange}</p>
      </div>

      <div className="email-content">
        {/* Overview Stats */}
        <div className="email-section">
          <h2>📊 This Week&apos;s Overview</h2>
          <div className="stats-container">
            <div className="stat-item">
              <span className="stat-value">{data.totalChatTime}</span>
              <span className="stat-label">Total chat time</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{data.sessionCount}</span>
              <span className="stat-label">Conversations</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{data.avgSession} mins</span>
              <span className="stat-label">Average length</span>
            </div>
          </div>
        </div>

        {/* Emotional Wellbeing */}
        <div className="email-section">
          <h2>😊 Emotional Wellbeing</h2>
          <p>
            <strong>Overall mood:</strong> {data.overallMood}
          </p>
          <p>{data.moodDetails}</p>
        </div>

        {/* Interests & Learning */}
        <div className="email-section">
          <h2>🎯 Interests & Learning</h2>
          <p>
            <strong>Main interests:</strong> {data.mainInterests}
          </p>
          <p>
            <strong>Learning moments:</strong> {data.learningMoments}
          </p>
        </div>

        {/* Social & Emotional (conditional) */}
        {data.socialEmotional && (
          <div className="email-section">
            <h2>👥 Social & Emotional</h2>
            <p>{data.socialEmotional}</p>
          </div>
        )}

        {/* Safety Status */}
        <div className="email-section">
          <h2>🛡️ Safety Status</h2>
          <p className={data.safetyClass}>{data.safetyStatusText}</p>
          {data.safetyDetails && <p>{data.safetyDetails}</p>}
        </div>

        {/* Highlights (conditional) */}
        {data.highlights.length > 0 && (
          <div className="email-section">
            <h2>✨ This Week&apos;s Highlights</h2>
            {data.highlights.map((highlight, index) => (
              <div key={index} className="highlight-box">
                {highlight}
              </div>
            ))}
          </div>
        )}

        {/* Family Conversation Starters */}
        <div className="email-section">
          <h2>💬 Family Conversation Starters</h2>
          <div className="conversation-starters">
            <p>
              Here are some questions to spark meaningful conversations with{' '}
              {data.childName}:
            </p>
            <ul>
              {data.suggestedConversations.map((conversation, index) => (
                <li key={index}>{conversation}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="email-footer">
          <p>
            Generated by Onda AI •<a href={data.dashboardUrl}>View Dashboard</a>{' '}
            •<a href={data.unsubscribeUrl}>Email Settings</a>
          </p>
          <p style={{ marginTop: '10px', fontSize: '12px', color: '#9ca3af' }}>
            This summary is generated using privacy-safe analysis of
            conversation patterns.
            <br />
            Full conversation content is never stored or shared.
          </p>
        </div>
      </div>
    </BaseEmailTemplate>
  );
};
